### PR TITLE
Support custom schema property

### PR DESCRIPTION
**Pull request by nijikokun**
Our schema uses `primaryEmail` instead of `email` and since the code is pre-existing this makes it difficult for us to change over, however, by changing the module to allow changing the property we no longer need to have a custom plugin to do essentially what this plugin does.

### CODE REVIEW

**Comment by cristiandouce** [comment]
Amazing! thanks!
Would you mind updating what I just pointed so I can merge?

**Comment by cristiandouce** [comment]
Maybe a test if possible.

**Comment by nijikokun** [comment]
> I'd rather add a ## Plugin options list category above this, because this must be passed to the plugin on initialization.

It is on both initialization and the gravatar method, I can update the readme in a moment, I am creating another pull request that addresses another issue

**Comment by cristiandouce** [comment]
Yes! Though I'd like to keep a difference between plugin specific options and gravatar's.

Never mind about the Readme, I can update it later. But if you can add a test, that's enough to me.

**Comment by nijikokun** [comment]
15.1 passed,
15.2 failed due to the before hook but that's preposterous, I've tried many times to get it to fail maybe it's a travis issue, and I cannot re-run the test on travis: 

``` js
  mongoose-gravatar
    .gravatar()
      ✓ should build a base gravatar url without params
      ✓ should update gravatar when changing email
      ✓ should support different schema properties
      ✓ should build a base gravatar url with plugin's options params
    .gravatar(params)
      ✓ should use secure url
      ✓ should compile a query string when API params provided
      ✓ should generate different url with an email provided
      ✓ should override plugin's options with API params provided


  8 passing (35 ms)
```

If you could re-run the test, that would be great; It requires write access.

**Pull request merged**
